# Site settings
title: Ewan Blog 
header-img: img/home-bg.jpg
email: zhang21507@gmail.com
description: " Ewan Zhang 的个人博客 "
baseurl: ""
url: "http://www.ewanzhang.com/"
twitter_username: Ewan
github_username:  Ewan
facebook_username:  Ewan
weibo_username: Ewan
zhihu_username: Ewan

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
